### ISSUE TITLE
关于COSNet复现问题

### ISSUE THREAD

**Issue by chssjhjbj** [Wangyf1998/FTL#1]
我在训练COSNet史，遇到了这个：
 (predictor): BasePredictor(
    (logits): Linear(in_features=512, out_features=10200, bias=True)
    (dropout): Dropout(p=0.5, inplace=False)
  )
  (greedy_decoder): GreedyDecoder()
  (beam_searcher): BeamSearcher()
)
[09/08 16:48:14] xl.datasets.common INFO: Serializing 113287 elements to byte tensors and concatenating them all ...
[09/08 16:48:23] xl.datasets.common INFO: Serialized dataset takes 162.52 MiB
[09/08 16:48:23] xl.datasets.common INFO: Serializing 5000 elements to byte tensors and concatenating them all ...
[09/08 16:48:23] xl.datasets.common INFO: Serialized dataset takes 2.68 MiB
[09/08 16:48:23] xl.datasets.common INFO: Serializing 5000 elements to byte tensors and concatenating them all ...
[09/08 16:48:23] xl.datasets.common INFO: Serialized dataset takes 2.68 MiB
[09/08 16:48:39] fvcore.common.checkpoint INFO: [Checkpointer] Loading from /home/stormai/userfile/caoshan/code/xmodaler/ModelResult/xe/cosnet_xe.pth ...
[09/08 16:48:44] xl.engine.train_loop INFO: Starting training from iteration 0
[09/08 16:48:45] xl.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "/home/stormai/userfile/caoshan/code/xmodaler-master/xmodaler/engine/train_loop.py", line 151, in train
    self.run_step()
  File "/home/stormai/userfile/caoshan/code/xmodaler-master/xmodaler/engine/rl_mean_trainer.py", line 47, in run_step
    bs_rewards = self.scorer(bs_outputs_dict)
  File "/home/stormai/userfile/caoshan/code/xmodaler-master/xmodaler/scorer/base_scorer.py", line 66, in __call__
    gts = [self.gts[i] for i in ids]
  File "/home/stormai/userfile/caoshan/code/xmodaler-master/xmodaler/scorer/base_scorer.py", line 66, in <listcomp>
    gts = [self.gts[i] for i in ids]
TypeError: list indices must be integers or slices, not numpy.str_

请问您有遇到过吗？如何解决的呀？

**Comment by Wangyf1998** [comment]
您好！我没有使用强化学习进行训练，所以没有遇到这个问题。看问题描述应该是ids里包含了np.str类型的元素，无法传入gts[i]。你最好检查一下ids的元素是否有误，然后试试看用ids.to_list()或者别的什么转换类型的语句能不能解决问题。

**Comment by chssjhjbj** [comment]
谢谢您的回复。我已经试过强制转换了，像ids = ids.tolist()，gts = [self.gts[i] for i in int(ids.tolist())]，还是会报错

**Comment by Wangyf1998** [comment]
那可能就要单步调试看一下ids的值是不是有问题了，道理上讲ids是从作者提供的kpl文件里得到的，如果你用的全部是作者提供的文件，那最好还是邮件咨询一下作者。

**Comment by chssjhjbj** [comment]
好的感谢！我也这么觉得，我去作者GitHub也问下吧。
